"""Reusable helpers for Blender parameter-sweep visual workbenches."""

from .artifact_index import (
    ArtifactDescriptor,
    build_artifact_index,
    format_artifact_report,
    scan_artifacts,
    validate_artifact_index,
)
from .artifact_fingerprint import fingerprint_status, make_artifact_fingerprint, render_cache_fingerprint
from .camera import add_orbit_camera, camera_distance_for_matching_framing, look_at, orbit_location
from .capabilities import collect_capability_report, expand_required_tools, format_capability_report
from .example_manifest import ExamplePreflight, format_preflight_report, load_manifest, preflight_examples
from .example_pick_smoke import PickSmokePlan, PickSmokeResult, pick_smoke_plans, run_pick_smoke, verify_selected_json
from .fixtures import FixtureStatus, fixture_builder, fixture_statuses, load_fixture_registry, validate_fixture_registry
from .handoff import build_handoff_prompt_card, format_handoff_markdown, prompt_card_from_reference_prompt, write_handoff_card
from .image_diagnostics import analyze_sweep_images, format_diagnostics_readme
from .learning_coverage import format_learning_coverage_report, uncovered_learning_prompts, validate_learning_coverage
from .new_scout import ScoutPlan, build_scout_plan, format_scout_plan, write_scout_scaffold
from .postprocess import (
    PostprocessLookSettings,
    coerce_postprocess_look_settings,
    magick_look_postprocess,
    postprocess_look_variants,
    render_postprocess_sweep,
)
from .presets import RENDER_PRESETS, SWEEP_AXES, TILE_PRESETS, SweepAxis, one_axis_variants, seed_stride_axis, stride_axis, two_axis_variants
from .primitives import add_soft_horizon_band, soft_band_alpha_profile
from .promote import import_recipe_callable, load_sweep_variants, promote_from_metadata, select_metadata_variant
from .promotion_status import PromotionStatus, format_promotion_report, promotion_statuses
from .review_log import load_review_log, review_summary, selected_pick_from_review, write_review_log
from .review_page import write_review_page
from .sweep import (
    RenderConfig,
    RenderResult,
    ReferenceTarget,
    SweepVariant,
    TileSpec,
    VARIANT_ROLES,
    configure_render,
    coerce_profile_comparison_profiles,
    coerce_reference_targets,
    default_profile_comparison_profiles,
    format_reference_targets_readme,
    grid_variants,
    infer_procedural_controls,
    named_variants,
    normalize_procedural_controls,
    normalize_variant_role,
    normalize_variant_tags,
    PROTECTED_PROMOTION_ROLES,
    PROCEDURAL_SETTING_KEYS,
    profile_drift_warnings,
    replicate_variants,
    render_profile_comparison,
    render_profile_comparison_from_sweep,
    render_selected_from_sweep,
    render_selected_replicates,
    render_selected_replicates_from_sweep,
    render_selected_variant,
    render_sweep,
    select_variant,
    variants_from_sweep_metadata,
    write_profile_comparison_readme,
    write_reference_attempt_pair,
    write_sweep_diagnostics,
)

__all__ = [
    "add_orbit_camera",
    "add_soft_horizon_band",
    "analyze_sweep_images",
    "ArtifactDescriptor",
    "build_artifact_index",
    "build_handoff_prompt_card",
    "build_scout_plan",
    "camera_distance_for_matching_framing",
    "fingerprint_status",
    "collect_capability_report",
    "coerce_postprocess_look_settings",
    "ExamplePreflight",
    "FixtureStatus",
    "fixture_builder",
    "fixture_statuses",
    "format_artifact_report",
    "format_diagnostics_readme",
    "format_preflight_report",
    "format_capability_report",
    "format_handoff_markdown",
    "format_learning_coverage_report",
    "format_scout_plan",
    "RenderConfig",
    "RenderResult",
    "ReferenceTarget",
    "RENDER_PRESETS",
    "SWEEP_AXES",
    "SweepAxis",
    "SweepVariant",
    "TILE_PRESETS",
    "TileSpec",
    "VARIANT_ROLES",
    "configure_render",
    "coerce_profile_comparison_profiles",
    "coerce_reference_targets",
    "default_profile_comparison_profiles",
    "format_reference_targets_readme",
    "grid_variants",
    "infer_procedural_controls",
    "expand_required_tools",
    "import_recipe_callable",
    "load_manifest",
    "load_fixture_registry",
    "load_review_log",
    "load_sweep_variants",
    "look_at",
    "make_artifact_fingerprint",
    "named_variants",
    "normalize_procedural_controls",
    "normalize_variant_role",
    "normalize_variant_tags",
    "one_axis_variants",
    "orbit_location",
    "PickSmokePlan",
    "PickSmokeResult",
    "pick_smoke_plans",
    "magick_look_postprocess",
    "PostprocessLookSettings",
    "PROTECTED_PROMOTION_ROLES",
    "PROCEDURAL_SETTING_KEYS",
    "postprocess_look_variants",
    "replicate_variants",
    "render_postprocess_sweep",
    "render_cache_fingerprint",
    "promote_from_metadata",
    "PromotionStatus",
    "format_promotion_report",
    "promotion_statuses",
    "prompt_card_from_reference_prompt",
    "preflight_examples",
    "profile_drift_warnings",
    "render_profile_comparison",
    "render_profile_comparison_from_sweep",
    "render_selected_from_sweep",
    "render_selected_replicates",
    "render_selected_replicates_from_sweep",
    "render_selected_variant",
    "render_sweep",
    "run_pick_smoke",
    "scan_artifacts",
    "ScoutPlan",
    "select_metadata_variant",
    "selected_pick_from_review",
    "select_variant",
    "seed_stride_axis",
    "soft_band_alpha_profile",
    "stride_axis",
    "two_axis_variants",
    "validate_artifact_index",
    "validate_fixture_registry",
    "uncovered_learning_prompts",
    "validate_learning_coverage",
    "variants_from_sweep_metadata",
    "verify_selected_json",
    "review_summary",
    "write_review_page",
    "write_handoff_card",
    "write_profile_comparison_readme",
    "write_reference_attempt_pair",
    "write_review_log",
    "write_scout_scaffold",
    "write_sweep_diagnostics",
]
