"""Optional scene recipes built on the generic workbench helpers."""

from .camera_perspective import (
    CAMERA_PERSPECTIVE_CAMERA,
    CameraPerspectiveSettings,
    build_camera_perspective_scene,
    camera_perspective_variants,
    coerce_camera_perspective_settings,
)
from .caustic_water import (
    CAUSTIC_WATER_CAMERA,
    CausticWaterSettings,
    build_caustic_water_scene,
    caustic_water_descriptor,
    caustic_water_variants,
    coerce_caustic_water_settings,
)
from .depth_of_field import (
    DEPTH_OF_FIELD_CAMERA,
    DepthOfFieldSettings,
    build_depth_of_field_scene,
    coerce_depth_of_field_settings,
    depth_of_field_descriptor,
    depth_of_field_variants,
    focus_plane_targets,
)
from .diffuser_light_object import (
    DIFFUSER_LIGHT_OBJECT_CAMERA,
    DiffuserLightObjectSettings,
    build_diffuser_light_object_scene,
    coerce_diffuser_light_object_settings,
    diffuser_light_object_descriptor,
    diffuser_light_object_variants,
)
from .gobo_lighting import GOBO_CAMERA, GoboLightingSettings, build_gobo_lighting_scene, coerce_gobo_settings, gobo_lighting_variants
from .layered_material import (
    LAYERED_MATERIAL_CAMERA,
    LayeredMaterialSettings,
    build_layered_material_scene,
    coerce_layered_material_settings,
    layered_material_variants,
    layered_material_weight_summary,
)
from .long_exposure_moonrise import (
    LONG_EXPOSURE_MOONRISE_CAMERA,
    LongExposureMoonriseSettings,
    build_long_exposure_moonrise_scene,
    coerce_long_exposure_moonrise_settings,
    long_exposure_moonrise_variants,
    moonrise_trail_descriptor,
)
from .metal_edge_light import (
    METAL_EDGE_LIGHT_CAMERA,
    MetalEdgeLightSettings,
    build_metal_edge_light_scene,
    coerce_metal_edge_light_settings,
    metal_edge_light_variants,
)
from .mesh_light import MESH_LIGHT_CAMERA, MeshLightSettings, build_mesh_light_scene, coerce_mesh_light_settings, mesh_light_variants
from .procedural_texture import (
    PROCEDURAL_TEXTURE_CAMERA,
    ProceduralTextureSettings,
    build_procedural_texture_scene,
    coerce_procedural_texture_settings,
    procedural_texture_descriptor,
    procedural_texture_variants,
)
from .rocket_plume import (
    ROCKET_PLUME_CAMERA,
    RocketPlumeSettings,
    build_rocket_plume_scene,
    coerce_rocket_plume_settings,
    rocket_plume_scout_variants,
    rocket_plume_texture_variants,
)
from .silhouette_shape import (
    SILHOUETTE_SHAPE_CAMERA,
    SilhouetteShapeSettings,
    build_silhouette_shape_scene,
    coerce_silhouette_shape_settings,
    silhouette_shape_variants,
)
from .smoke_billboard import (
    SMOKE_BILLBOARD_CAMERA,
    SmokeBillboardSettings,
    build_smoke_billboard_scene,
    coerce_smoke_billboard_settings,
    smoke_billboard_descriptor,
    smoke_billboard_variants,
)
from .soft_atmosphere import (
    SOFT_ATMOSPHERE_CAMERA,
    SoftAtmosphereSettings,
    build_soft_atmosphere_scene,
    coerce_soft_atmosphere_settings,
    soft_atmosphere_variants,
)
from .subsurface import (
    SUBSURFACE_CAMERA,
    SubsurfaceSettings,
    build_subsurface_scene,
    coerce_subsurface_settings,
    subsurface_variants,
)
from .sunset_haze import SUNSET_HAZE_CAMERA, SunsetHazeSettings, build_sunset_haze_scene, coerce_sunset_haze_settings, sunset_haze_variants
from .terrain_environment import (
    TERRAIN_ENVIRONMENT_CAMERA,
    TerrainEnvironmentSettings,
    build_terrain_environment_scene,
    coerce_terrain_environment_settings,
    terrain_environment_variants,
)
from .transparency import (
    TRANSPARENCY_CAMERA,
    TransparencySettings,
    build_transparency_scene,
    coerce_transparency_settings,
    transparency_variants,
)

__all__ = [
    "CAMERA_PERSPECTIVE_CAMERA",
    "CameraPerspectiveSettings",
    "CAUSTIC_WATER_CAMERA",
    "CausticWaterSettings",
    "DEPTH_OF_FIELD_CAMERA",
    "DepthOfFieldSettings",
    "DIFFUSER_LIGHT_OBJECT_CAMERA",
    "DiffuserLightObjectSettings",
    "GOBO_CAMERA",
    "GoboLightingSettings",
    "LAYERED_MATERIAL_CAMERA",
    "LayeredMaterialSettings",
    "LONG_EXPOSURE_MOONRISE_CAMERA",
    "LongExposureMoonriseSettings",
    "METAL_EDGE_LIGHT_CAMERA",
    "MetalEdgeLightSettings",
    "MESH_LIGHT_CAMERA",
    "MeshLightSettings",
    "PROCEDURAL_TEXTURE_CAMERA",
    "ProceduralTextureSettings",
    "ROCKET_PLUME_CAMERA",
    "RocketPlumeSettings",
    "SILHOUETTE_SHAPE_CAMERA",
    "SilhouetteShapeSettings",
    "SMOKE_BILLBOARD_CAMERA",
    "SmokeBillboardSettings",
    "SOFT_ATMOSPHERE_CAMERA",
    "SoftAtmosphereSettings",
    "SUBSURFACE_CAMERA",
    "SubsurfaceSettings",
    "SUNSET_HAZE_CAMERA",
    "SunsetHazeSettings",
    "TERRAIN_ENVIRONMENT_CAMERA",
    "TerrainEnvironmentSettings",
    "TRANSPARENCY_CAMERA",
    "TransparencySettings",
    "build_camera_perspective_scene",
    "build_caustic_water_scene",
    "build_depth_of_field_scene",
    "build_diffuser_light_object_scene",
    "build_gobo_lighting_scene",
    "build_layered_material_scene",
    "build_long_exposure_moonrise_scene",
    "build_metal_edge_light_scene",
    "build_mesh_light_scene",
    "build_procedural_texture_scene",
    "build_rocket_plume_scene",
    "build_silhouette_shape_scene",
    "build_smoke_billboard_scene",
    "build_soft_atmosphere_scene",
    "build_subsurface_scene",
    "build_sunset_haze_scene",
    "build_terrain_environment_scene",
    "build_transparency_scene",
    "caustic_water_descriptor",
    "caustic_water_variants",
    "camera_perspective_variants",
    "coerce_caustic_water_settings",
    "coerce_camera_perspective_settings",
    "coerce_depth_of_field_settings",
    "coerce_diffuser_light_object_settings",
    "coerce_gobo_settings",
    "coerce_layered_material_settings",
    "coerce_long_exposure_moonrise_settings",
    "coerce_metal_edge_light_settings",
    "coerce_mesh_light_settings",
    "coerce_procedural_texture_settings",
    "coerce_rocket_plume_settings",
    "coerce_silhouette_shape_settings",
    "coerce_smoke_billboard_settings",
    "coerce_soft_atmosphere_settings",
    "coerce_subsurface_settings",
    "coerce_sunset_haze_settings",
    "coerce_terrain_environment_settings",
    "coerce_transparency_settings",
    "depth_of_field_descriptor",
    "depth_of_field_variants",
    "diffuser_light_object_descriptor",
    "diffuser_light_object_variants",
    "focus_plane_targets",
    "gobo_lighting_variants",
    "layered_material_variants",
    "layered_material_weight_summary",
    "long_exposure_moonrise_variants",
    "metal_edge_light_variants",
    "mesh_light_variants",
    "moonrise_trail_descriptor",
    "procedural_texture_descriptor",
    "procedural_texture_variants",
    "rocket_plume_scout_variants",
    "rocket_plume_texture_variants",
    "silhouette_shape_variants",
    "smoke_billboard_descriptor",
    "smoke_billboard_variants",
    "soft_atmosphere_variants",
    "subsurface_variants",
    "sunset_haze_variants",
    "terrain_environment_variants",
    "transparency_variants",
]
