"""Optional scene recipes built on the generic workbench helpers."""

from .camera_perspective import (
    CAMERA_PERSPECTIVE_CAMERA,
    CameraPerspectiveSettings,
    build_camera_perspective_scene,
    camera_perspective_variants,
    coerce_camera_perspective_settings,
)
from .gobo_lighting import GOBO_CAMERA, GoboLightingSettings, build_gobo_lighting_scene, coerce_gobo_settings, gobo_lighting_variants
from .layered_material import (
    LAYERED_MATERIAL_CAMERA,
    LayeredMaterialSettings,
    build_layered_material_scene,
    coerce_layered_material_settings,
    layered_material_variants,
    layered_material_weight_summary,
)
from .mesh_light import MESH_LIGHT_CAMERA, MeshLightSettings, build_mesh_light_scene, coerce_mesh_light_settings, mesh_light_variants
from .procedural_texture import (
    PROCEDURAL_TEXTURE_CAMERA,
    ProceduralTextureSettings,
    build_procedural_texture_scene,
    coerce_procedural_texture_settings,
    procedural_texture_descriptor,
    procedural_texture_variants,
)
from .rocket_plume import (
    ROCKET_PLUME_CAMERA,
    RocketPlumeSettings,
    build_rocket_plume_scene,
    coerce_rocket_plume_settings,
    rocket_plume_scout_variants,
    rocket_plume_texture_variants,
)
from .silhouette_shape import (
    SILHOUETTE_SHAPE_CAMERA,
    SilhouetteShapeSettings,
    build_silhouette_shape_scene,
    coerce_silhouette_shape_settings,
    silhouette_shape_variants,
)
from .soft_atmosphere import (
    SOFT_ATMOSPHERE_CAMERA,
    SoftAtmosphereSettings,
    build_soft_atmosphere_scene,
    coerce_soft_atmosphere_settings,
    soft_atmosphere_variants,
)
from .subsurface import (
    SUBSURFACE_CAMERA,
    SubsurfaceSettings,
    build_subsurface_scene,
    coerce_subsurface_settings,
    subsurface_variants,
)
from .sunset_haze import SUNSET_HAZE_CAMERA, SunsetHazeSettings, build_sunset_haze_scene, coerce_sunset_haze_settings, sunset_haze_variants
from .terrain_environment import (
    TERRAIN_ENVIRONMENT_CAMERA,
    TerrainEnvironmentSettings,
    build_terrain_environment_scene,
    coerce_terrain_environment_settings,
    terrain_environment_variants,
)
from .transparency import (
    TRANSPARENCY_CAMERA,
    TransparencySettings,
    build_transparency_scene,
    coerce_transparency_settings,
    transparency_variants,
)

__all__ = [
    "CAMERA_PERSPECTIVE_CAMERA",
    "CameraPerspectiveSettings",
    "GOBO_CAMERA",
    "GoboLightingSettings",
    "LAYERED_MATERIAL_CAMERA",
    "LayeredMaterialSettings",
    "MESH_LIGHT_CAMERA",
    "MeshLightSettings",
    "PROCEDURAL_TEXTURE_CAMERA",
    "ProceduralTextureSettings",
    "ROCKET_PLUME_CAMERA",
    "RocketPlumeSettings",
    "SILHOUETTE_SHAPE_CAMERA",
    "SilhouetteShapeSettings",
    "SOFT_ATMOSPHERE_CAMERA",
    "SoftAtmosphereSettings",
    "SUBSURFACE_CAMERA",
    "SubsurfaceSettings",
    "SUNSET_HAZE_CAMERA",
    "SunsetHazeSettings",
    "TERRAIN_ENVIRONMENT_CAMERA",
    "TerrainEnvironmentSettings",
    "TRANSPARENCY_CAMERA",
    "TransparencySettings",
    "build_camera_perspective_scene",
    "build_gobo_lighting_scene",
    "build_layered_material_scene",
    "build_mesh_light_scene",
    "build_procedural_texture_scene",
    "build_rocket_plume_scene",
    "build_silhouette_shape_scene",
    "build_soft_atmosphere_scene",
    "build_subsurface_scene",
    "build_sunset_haze_scene",
    "build_terrain_environment_scene",
    "build_transparency_scene",
    "camera_perspective_variants",
    "coerce_camera_perspective_settings",
    "coerce_gobo_settings",
    "coerce_layered_material_settings",
    "coerce_mesh_light_settings",
    "coerce_procedural_texture_settings",
    "coerce_rocket_plume_settings",
    "coerce_silhouette_shape_settings",
    "coerce_soft_atmosphere_settings",
    "coerce_subsurface_settings",
    "coerce_sunset_haze_settings",
    "coerce_terrain_environment_settings",
    "coerce_transparency_settings",
    "gobo_lighting_variants",
    "layered_material_variants",
    "layered_material_weight_summary",
    "mesh_light_variants",
    "procedural_texture_descriptor",
    "procedural_texture_variants",
    "rocket_plume_scout_variants",
    "rocket_plume_texture_variants",
    "silhouette_shape_variants",
    "soft_atmosphere_variants",
    "subsurface_variants",
    "sunset_haze_variants",
    "terrain_environment_variants",
    "transparency_variants",
]
